aliases:
  restore_cache_step: &restore_cache_step
    restore_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
  save_cache_step: &save_cache_step
    save_cache:
      key: dependency-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules
  install_dependencies_step: &install_dependencies_step
    run:
      name: install-dependencies
      command: yarn install

version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_cache_step
      - *install_dependencies_step
      - *save_cache_step
      - run:
          name: Publish website
          command: ./script/rebuild --deploy

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
