#!/usr/bin/env bash

set -euo pipefail

COMMIT=true
FORCE=false
DEPLOY=false

while [ $# -gt 0 ]; do
  case $1 in
    --no-commit)
      COMMIT=false
      ;;

    --force|-f)
      FORCE=true
      ;;

    --deploy)
      DEPLOY=true
      ;;
  esac

  shift
done

if [ "${FORCE:-}" == false ]; then
  if [ "${TRAVIS_PULL_REQUEST:-}" != false ]; then
    echo "Refusing to update website on PR build (use --force to override)."
    exit 0
  fi

  if [ "${TRAVIS_BRANCH:-}" != master ]; then
    echo "Refusing to update website on non-master build (use --force to override)."
    exit 0
  fi
fi

source $(dirname $0)/helpers.sh

# Get the current version.
VERSION=$(./script/latest-version decaffeinate)

configureGithubRemote decaffeinate/decaffeinate-project.org

# Build the browser version.
browserify \
  --require decaffeinate \
  --ignore mz \
  --ignore @babel/generator \
  --ignore prettier \
  --standalone decaffeinate \
  --outfile scripts/decaffeinate.js

# Update the script in the gh-pages branch.
perl -p -i -e "s/v\d+\.\d+\.\d+/v${VERSION}/" repl/index.html

if hasChanges; then
  if [ ${COMMIT} == true ]; then
    echo "Committing changes for ${VERSION}…"
    git add repl/index.html scripts/decaffeinate.js
    git commit -m "chore(package): update decaffeinate.js to ${VERSION}"

    if [ "${DEPLOY}" == true ]; then
      echo "Pushing to gh-pages…"
      git push -f origin HEAD:gh-pages
    fi
  else
    echo "Not committing changes since --no-commit was given."
  fi
fi
