#!/usr/bin/env bash

set -euo pipefail

COMMIT=true
DEPLOY=false

while [ $# -gt 0 ]; do
  case $1 in
    --no-commit)
      COMMIT=false
      ;;

    --deploy)
      DEPLOY=true
      ;;
  esac

  shift
done

source $(dirname $0)/helpers.sh

# Get the current version.
VERSION=$(./script/latest-version decaffeinate)

configureGithubRemote decaffeinate/decaffeinate-project.org

# Build the browser version.
browserify \
  --require decaffeinate \
  --ignore mz \
  --ignore @babel/generator \
  --ignore prettier \
  --standalone decaffeinate \
  --outfile scripts/decaffeinate.js

# Update the script & version.
perl -p -i -e "s/v\d+\.\d+\.\d+/v${VERSION}/" repl/index.html

if ! git config user.name > /dev/null; then
  git config user.name "Decaffeinate CI"
fi

if ! git config user.email > /dev/null; then
  git config user.email "1938+eventualbuddha@users.noreply.github.com"
fi

if hasChanges; then
  if [ ${COMMIT} == true ]; then
    echo "Committing changes for ${VERSION}…"
    git add repl/index.html scripts/decaffeinate.js
    git commit -m "chore(package): update decaffeinate.js to ${VERSION}"

    if [ "${DEPLOY}" == true ]; then
      echo "Pushing to origin…"
      git push -f origin HEAD:main
    fi
  else
    echo "Not committing changes since --no-commit was given."
  fi
fi
