#!/usr/bin/env bash

COMMIT=true
FORCE=false

while [ $# -gt 0 ]; do
  case $1 in
    --no-commit)
      COMMIT=false
      ;;

    --force|-f)
      FORCE=true
      ;;
  esac

  shift
done

if [[ "${FORCE}" != true && "${TRAVIS_PULL_REQUEST}" != false ]]; then
  echo "Refusing to update website on PR build (use --force to override)."
  exit 0
fi

source $(dirname $0)/helpers.sh

# Get the current version.
VERSION=$(./script/latest-version decaffeinate)

configureGithubRemote decaffeinate/decaffeinate-project.org

# Build the browser version.
browserify -e node_modules/decaffeinate/dist/decaffeinate.js -s decaffeinate -o scripts/decaffeinate.js

# Update the script in the gh-pages branch.
perl -p -i -e "s/v\d+\.\d+\.\d+/v$VERSION/" repl/index.html

if hasChanges; then
  if [ ${COMMIT} == true ]; then
    git commit -av -m "Update decaffeinate.js."
    git push origin HEAD:gh-pages
  else
    echo "Not committing changes since --no-commit was given."
  fi
fi
