name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install

      - name: Publish website
        run: ./script/rebuild --deploy
